vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        product_images:
            uri_prefix: /uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

        user_images:
            uri_prefix: /uploads/images/users
            upload_destination: '%kernel.project_dir%/public/uploads/images/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
